config/routes.rb
Rails.application.routes.draw do
  resources :user, only: [:show, :index]

  resources :wikis

  resources :wikis do
    resources :collaborators, only: [:create, :destroy]
  end

  resources :charges, only: [:new, :create]

  devise_for :users, :controllers => {:registrations => "registrations"}

  get 'about' => 'welcome#about'

  root 'welcome#index'

  resources :user do
    member do
      post :downgrade_account
    end
  end

end

app/models/collaborator.rb
class Collaborator < ActiveRecord::Base
  belongs_to :user
  belongs_to :wiki

  @user_options = User.all.map {|u| [u.email, u.id]}
end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController

    def new
        @collaborator = Collaborator.new
    end

    def create
        wiki = Wiki.find(params[:wiki_id])
        user = User.find(params[:user_id])
        @collaborator = Collaborator.new(wiki_id: wiki.id, user_id: user.id)

        if @collaborator.save
            flash[:notice] = "Collaborator added to Wiki"
        else
            flash[:alert] = "Unable to add collaborator."
        end

        redirect_to [wiki]
    end

    def destroy
        @wiki = Wiki.find(params[:wiki_id])
        @collaborator = Collaborator.find(params[:id])

        if @collaborator.destroy
  		    flash[:notice] = "User was successfully removed as collaborator."
  		    redirect_to @wiki
  	    else
  		    flash.now[:alert] = "There was an error removing the collaborator."
  		    render :show
  	    end
    end

end

app/helpers/collaborators_helper.rb
module CollaboratorsHelper
end

app/views/collaborators/_form.html.erb
<% if @wiki.user_id == current_user.id || current_user.admin? %>
    <div class="form-group">
        <% @users.each do |user| %>
            <h5><%= user.email %></h5>

            <% if @wiki.users.include? user %>
                <div>
                    <%= link_to "Remove Collaborator", wiki_collaborator_path(@wiki, @wiki.collaborators.find_by_user_id(user.id).id), method: :delete, class: 'btn btn-danger' %>
                </div>
            <% else %>
                <div>
                    <%= link_to "Add Collaborator", wiki_collaborators_path(@wiki, user_id: user.id), method: :create, class: 'btn btn-warning' %>
                </div>
            <% end %>
        <% end %>
    </div>
<% end %>