config/routes.rb
Rails.application.routes.draw do
  resources :user, only: [:show, :index]

  resources :wikis

  resources :wikis do
    resources :collaborators, only: [:create, :destroy]
  end

  resources :charges, only: [:new, :create]

  devise_for :users, :controllers => {:registrations => "registrations"}

  get 'about' => 'welcome#about'

  root 'welcome#index'

  resources :user do
    member do
      post :downgrade_account
    end
  end

end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  belongs_to :user
  has_many :collaborators, dependent: :destroy
  has_many :users, through: :collaborators
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  before_action :authenticate_user!

  def index
    @wikis = Wiki.all
  end

  def show
    @wiki = Wiki.find(params[:id])
  end

  def new
    @wiki = Wiki.new
  end

  def create
    @wiki = Wiki.new
    @wiki.title = params[:wiki][:title]
    @wiki.body = params[:wiki][:body]
    @wiki.private = params[:wiki][:private]

    if @wiki.save
      flash[:notice] = "Wiki was saved."
      redirect_to wikis_path
    else
      flash.now[:alert] = "There was an error saving the wiki. Please try again."
      render :new
    end
  end

  def edit
    @wiki = Wiki.find(params[:id])
  end

  def update
    @wiki = Wiki.find(params[:id])
    @wiki.title = params[:wiki][:title]
    @wiki.body = params[:wiki][:body]

    if @wiki.save
      flash[:notice] = "Wiki was updated."
      redirect_to wikis_path
    else
      flash.now[:alert] = "There was an error saving the wiki. Please try again."
      render :edit
    end
  end

  def destroy
    @wiki = Wiki.find(params[:id])

    if @wiki.destroy
      flash[:notice] = "\"#{@wiki.title}\" was deleted successfully."
      redirect_to wiki_path
    else
      flash.now[:alert] = "There was an error deleting the wiki."
      render :show
    end
  end
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/wikis/_form.html.erb
<%= form_for [wiki] do |f| %>
    <% if wiki.errors.any? %>
        <div class="alert alert-danger">
            <h4><%= pluralize(wiki.errors.count, "error") %>.</h4>
            <ul>
                <% wiki.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <%= form_group_tag(wiki.errors[:title]) do %>
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
    <% end %>
    <%= form_group_tag(wiki.errors[:body]) do %>
        <%= f.label :body %>
        <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
    <% end %>
    <% if current_user.admin? || current_user.premium? %>
        <div class="form-group">
            <%= f.label :private, class: 'checkbox' do %>
            <%= f.check_box :private %> Private wiki
        <% end %>
        </div>
    <% end %>
    <% if @wiki.private %>
        <%= render partial: 'collaborators/form', locals: {f: f} %>
    <% end %>

        <div class="form-group">
            <%= f.submit "Save", class: 'btn btn-success' %>
        </div>
<% end %>

app/views/wikis/edit.html.erb
<div class="row">
    <div class="col-md-8">
        <%= render partial: 'form', locals: {wiki: @wiki } %>
    </div>
</div>

app/views/wikis/index.html.erb
<div>
    <h1>Wikis</h1>
    <%= link_to "New Wiki", new_wiki_path(@wiki), class: 'btn btn-primary' %>
</div>


<% @wikis.each do |wiki| %>
    <div class="media">
        <div class="media-body">
            <h4 class="media-heading">
                <%= link_to wiki.title, wiki %>
            </h4>
        </div>
    </div>
<% end %>

app/views/wikis/new.html.erb
<div class="row">
    <div class="col-md-8">
        <%= render partial: 'form', locals: {wiki: @wiki } %>
    </div>
</div>

app/views/wikis/show.html.erb
<h1><%= markdown(@wiki.title) %></h1>
<p><%= markdown(@wiki.body) %></p>

<div class="col-md-4">
    <%= link_to "Edit Wiki", edit_wiki_path(@wiki), class: 'btn btn-success' %>
    <%= link_to "Delete Wiki", [@wiki], method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this wiki?' } %>
</div>