config/routes.rb
Rails.application.routes.draw do
  resources :user, only: [:show, :index]

  resources :wikis

  resources :wikis do
    resources :collaborators, only: [:create, :destroy]
  end

  resources :charges, only: [:new, :create]

  devise_for :users, :controllers => {:registrations => "registrations"}

  get 'about' => 'welcome#about'

  root 'welcome#index'

  resources :user do
    member do
      post :downgrade_account
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  enum role: [:standard, :premium, :admin]
  after_initialize :set_default_role, :if => :new_record?

  has_many :wikis
  def set_default_role
    self.role ||= :standard
  end

  attr_accessor :username
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :collaborators, dependent: :destroy
  has_many :wikis, through: :collaborators

end

app/controllers/user_controller.rb
class UsersController < ApplicationController

  def downgrade
    @wikis = current_user.wikis

    @wikis.unscoped.update_all(private: 'false')
    current_user.update_attribute(:role, 'standard')

    flash[:notice] = "#{current_user.email} your account has been downgraded"
    redirect_to edit_user_registration_path
  end

end

app/helpers/user_helper.rb
module UserHelper
end

app/views/user/index.html.erb
<h1>Users</h1>
<% @users.each do |user| %>
    <div class="media">
        <div class="media-body">
            <h4 class="media-heading">
                <%= link_to user.email, user %>
            </h4>
        </div>
    </div>
<% end %>

app/views/user/show.html.erb
<h2><%= @user.username %></h2>
<h4><%= @user.email %></h4>
<h5><%= @user.role.capitalize %> Membership</h5>

<%= link_to "Upgrade to Premium!", new_charge_path, class: 'btn btn-success' %>